language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
script:
  - npm run export
  - rm out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: out
  target_branch: master
  fqdn: tarrafa.net
  on:
    branch: test
