language: node_js
node_js:
  - 10.18.0
install:
  - npm install
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: master
  on:
    branch: dev
